version: 2.1
jobs:
  build:
    docker:
      image: circleci/node:9.0.0
    steps:
      - checkout
      - run: 
          name: echo "yarn installing"
          command: |
            yarn install
            CI=true yarn run build
  test:
    docker:
      image: circleci/node:9.0.0
    steps:
      - checkout
      - run: 
          name: echo "testing"
          command: | 
            yarn install
            yarn test
  hithere:
    docker:
      image: circleci/node:9.0.0
    steps:
      - checkout
      - run:
          name: 'Linting'
          command: echo 'hello robots!!!'
workflows:
  version: 2.1
  build_test_and_lint:
    jobs:
      - build
      - hithere
      - test:
          requires: 
            - hithere