version: 2.1
jobs:
  build:
    machine:
      image: circleci/node:9.0
    steps:
      - checkout
      - run: echo "yarn installing"
      - run: yarn install
      - run: CI=true yarn run build
  test:
    machine:
      image: circleci/node:9.0
    steps:
      - checkout
      - run: echo "testing"
      - run: yarn install
      - run: yarn test
  hithere:
    machine:
      image: circleci/node:9.0
    steps:
      - checkout
      - run: echo 'hello robots!!!'
workflows:
  version: 2.1
  build_test_and_lint:
    jobs:
      - build
      - hithere
      - test:
        requires: 
          -hithere