version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.0.0
    steps:
      - checkout
      - run: echo "yarn installing"
      - run: yarn install
      - run: CI=true yarn run build
  test:
    docker:
      - image: circleci/node:8.0.0
    steps:
      - checkout
      - run: echo "testing"
      - run: yarn install
      - run: yarn test
  hithere:
    docker:
      - image: circleci/node:8.0.0
    steps:
      - checkout
      - run: echo 'Linting'
      - run: echo 'hello robots!!!'
workflows:
  version: 2
  build_test_and_hithere:
    jobs:
      - build
      - hithere
      - test:
          requires: 
            - hithere